main.exe: main.c reverse.c find_length.c vovel_frequency.c sort.c
	gcc main.c -o main.exe
	gcc reverse.c -o reverse.exe
	gcc find_length.c -o find_length.exe
	gcc vovel_frequency.c -o vovel_frequency.exe
	gcc sort.c -o sort.exe

clean:
	rm *.exe