main: main.c special_char_remover.c arranger.c create_fifo.c
	gcc main.c -o main
	gcc special_char_remover.c -o special_char_remover
	gcc arranger.c -o arranger
	gcc create_fifo.c -o create_fifo

clean: 
	rm main special_char_remover arranger